POST http://localhost/development/athenication/demo.php?token=1 HTTP/1.1
content-type: application/json

{
    "email": "sample@gmail.com",
    "password": "1234"
}
###
GET http://localhost/development/athenication/demo.php?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXBsZUBnbWFpbC5jb20iLCJuYW1lIjoic2FtcGxlQGdtYWlsLmNvbSIsInVzZXIiOjEsImxldmVsIjoxLCJwZXJtaXNpb25zIjpbInZpZXdfZGFzaGJvYXJkIl0sImNyZWF0ZWRfYXQiOiIyMDI0LTExLTE2IDIxOjExOjAxIiwiZXhwIjoxNzMxNzg3ODYxfQ.60_4inrIhknu0j805MtHHfERT_a7fmXcIGE5JuiaR9U HTTP/1.1
 
###


POST http://localhost/development/athenication/demo.php
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbXBsZUBnbWFpbC5jb20iLCJuYW1lIjoic2FtcGxlQGdtYWlsLmNvbSIsInVzZXIiOjEsImxldmVsIjoxLCJwZXJtaXNpb25zIjpbInZpZXdfZGFzaGJvYXJkIl0sImNyZWF0ZWRfYXQiOiIyMDI0LTExLTE2IDIxOjExOjAxIiwiZXhwIjoxNzMxNzg3ODYxfQ.60_4inrIhknu0j805MtHHfERT_a7fmXcIGE5JuiaR9U

{
    "A":1
}